version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dsup
    restart: always
    environment:
      POSTGRES_DB: db_dsup
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: pass_admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    name: postgres-data

  redis-data:
    name: redis-data
