# Generated by Django 4.0.4 on 2025-02-17 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_secdelmodel_delete_testingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecDelMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delegate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SecDel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.secdelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_delegate', 'joined_at'],
            },
        ),
    ]
