# Generated by Django 4.0.4 on 2025-02-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_secdelmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secdelmembers',
            old_name='SecDel',
            new_name='sec_del',
        ),
    ]
