# Generated by Django 4.0.4 on 2025-02-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_secdel_secdelmembers_sec_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='secdelmembers',
            name='vote_in_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='secdelmembers',
            name='vote_out_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
