# Generated by Django 4.0.4 on 2025-02-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_secdelmembers_vote_in_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdelmembers',
            name='vote_in_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
