# Generated by Django 4.0.4 on 2023-11-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congress', models.IntegerField()),
                ('number', models.CharField(max_length=50)),
                ('origin_chamber', models.CharField(max_length=50)),
                ('origin_chamber_code', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('bill_type', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('latest_action_date', models.DateField()),
                ('latest_action_text', models.TextField()),
                ('voting_start', models.DateField(blank=True, null=True)),
                ('voting_close', models.DateField(blank=True, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_by_fDel', models.BooleanField(default=False)),
                ('your_vote', models.CharField(choices=[('Y', 'Yea'), ('N', 'Nay'), ('Pr', 'Present'), ('Px', 'Proxy')], default='Px', max_length=2)),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
