# Generated by Django 4.0.4 on 2023-11-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bill_schedule_date_alter_bill_voting_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billvote',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
    ]
