# Generated by Django 4.0.4 on 2023-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_number_alter_billvote_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='advice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='text',
            field=models.TextField(),
        ),
    ]
