# Generated by Django 4.0.4 on 2023-11-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_advice_alter_bill_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billvote',
            old_name='voted_by',
            new_name='voted_by_fDel',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='dtally',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='ntally',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='update_date_including_text',
        ),
        migrations.AlterField(
            model_name='billvote',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billvote',
            name='vote_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
