# Generated by Django 4.0.4 on 2023-11-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rename_voted_by_billvote_voted_by_fdel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='advice',
        ),
    ]
