# Generated by Django 4.0.4 on 2022-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='legalName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
