# Generated by Django 4.0.4 on 2022-05-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_users_legalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='createdDate',
        ),
    ]
