# Generated by Django 4.0.4 on 2022-05-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_pod_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podmember',
            old_name='is_members',
            new_name='is_member',
        ),
    ]
