# Generated by Django 4.0.4 on 2022-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_rename_is_members_podmember_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
