# Generated by Django 4.0.4 on 2022-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_pod_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podmember',
            name='date_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
