# Generated by Django 4.0.4 on 2022-05-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_alter_podmember_date_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.districts'),
            preserve_default=False,
        ),
    ]
