# Generated by Django 4.0.4 on 2022-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_pod_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='podmember',
            name='member_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
