# Generated by Django 4.0.4 on 2022-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_podmember_member_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podmember',
            name='vote_to',
        ),
        migrations.RemoveField(
            model_name='podmember',
            name='voted',
        ),
        migrations.AddField(
            model_name='podmember',
            name='vote_in',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podmember',
            name='vote_out',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
