# Generated by Django 4.0.4 on 2022-05-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0014_remove_podmember_vote_in_remove_podmember_vote_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodMember_put_farward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.podmember')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
