# Generated by Django 4.0.4 on 2022-05-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_podmember_put_farward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podmember',
            options={'ordering': ['-is_delegate', 'date_joined']},
        ),
    ]
