# Generated by Django 4.0.4 on 2022-06-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_pod_inivitation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podmember_put_farward',
            old_name='delegated',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='podmember',
            name='date_left',
        ),
    ]
