# Generated by Django 4.0.4 on 2022-08-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_rename_inivitation_code_pod_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podmember_put_farward',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putFarward', to='vote.podmember'),
        ),
        migrations.AlterField(
            model_name='podmember_vote_in',
            name='condidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteIns', to='vote.podmember'),
        ),
        migrations.AlterField(
            model_name='podmember_vote_out',
            name='condidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteOuts', to='vote.podmember'),
        ),
    ]
