# Generated by Django 4.0.4 on 2023-01-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0021_pod_fdel_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodBackNForth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('message', models.TextField(max_length=5000)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.pod')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
