# Generated by Django 4.0.4 on 2023-10-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0023_bfhandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='podbacknforth',
            name='handle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.bfhandle'),
        ),
    ]
