# Generated by Django 4.0.4 on 2023-11-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0023_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
