# Generated by Django 4.0.4 on 2023-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_remove_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
                ('is_delegate', models.BooleanField(default=False)),
                ('is_activeCircle', models.BooleanField(default=False)),
            ],
        ),
    ]
