# Generated by Django 5.0.2 on 2025-01-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0041_alter_circlemember_put_forward_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.group'),
        ),
    ]
