# Generated by Django 5.0.2 on 2025-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0042_alter_group_parent_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='member_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
