# Generated by Django 4.0.4 on 2025-02-14 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0044_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecDel',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_dels', to='vote.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_dels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
