# Generated by Django 4.0.4 on 2025-02-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0044_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='vote.groupmember'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
