# Generated by Django 4.0.4 on 2025-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0045_remove_contactinfo_user_contactinfo_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
