# Generated by Django 4.0.4 on 2025-02-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0046_contactinfo_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.groupmember'),
        ),
        migrations.DeleteModel(
            name='GroupMemberContact',
        ),
    ]
